// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Biswodip Goj
// GENERATED by scripts/generate-site-capabilities.mjs from integrations/catalog.json.
// Do not edit by hand — edit the catalog and re-run: node scripts/generate-site-capabilities.mjs .

export type CapabilitySection = 'browser' | 'animation' | 'design' | 'backend' | 'security' | 'quality';

export interface Capability {
  id: string;
  name: string;
  section: CapabilitySection;
  desc: string;
  required: boolean;
  stars: number | null;
  repo: string;
}

export const CAPABILITY_COLOR: Record<CapabilitySection, string> = {
  "browser": "#00d4ff",
  "animation": "#8b5cf6",
  "design": "#ec4899",
  "backend": "#10b981",
  "security": "#ef4444",
  "quality": "#f59e0b"
};

export const CAPABILITY_LABEL: Record<CapabilitySection, string> = {
  "browser": "Browser",
  "animation": "Animation",
  "design": "Design",
  "backend": "Backend",
  "security": "Security",
  "quality": "Quality"
};

export const CAPABILITY_SECTIONS: CapabilitySection[] = ['browser', 'animation', 'design', 'backend', 'security', 'quality'];

export const CAPABILITY_TOTAL = 89;
export const CAPABILITY_REQUIRED = 45;

export const CAPABILITIES: Capability[] = [
  {
    "id": "lightpanda-browser",
    "name": "Lightpanda Browser",
    "section": "browser",
    "desc": "Headless browser built for AI and automation in Zig. Extremely low memory and fast startup; CDP-compatible so it drops in where...",
    "required": false,
    "stars": 35600,
    "repo": "https://github.com/lightpanda-io/browser"
  },
  {
    "id": "stagehand",
    "name": "Browserbase Stagehand",
    "section": "browser",
    "desc": "SDK to extract data and interact with any site using natural language plus code. Pairs with Playwright/CDP for agent-driven bro...",
    "required": false,
    "stars": 25400,
    "repo": "https://github.com/browserbase/stagehand"
  },
  {
    "id": "skyvern",
    "name": "Skyvern",
    "section": "browser",
    "desc": "Automate browser-based workflows with AI and computer vision. Resilient to layout changes; good for form-heavy workflows.",
    "required": false,
    "stars": 23100,
    "repo": "https://github.com/Skyvern-AI/skyvern"
  },
  {
    "id": "steel-browser",
    "name": "Steel Browser",
    "section": "browser",
    "desc": "Open-source browser API and sandbox for AI agents and apps. Batteries-included session management without owning infrastructure.",
    "required": false,
    "stars": 7700,
    "repo": "https://github.com/steel-dev/steel-browser"
  },
  {
    "id": "browsermcp",
    "name": "Browser MCP",
    "section": "browser",
    "desc": "MCP server that lets AI applications control the browser through an extension. Useful for interactive visual QA.",
    "required": false,
    "stars": 7100,
    "repo": "https://github.com/BrowserMCP/mcp"
  },
  {
    "id": "jev-ultrafast",
    "name": "Jev Ultrafast",
    "section": "browser",
    "desc": "Default browser driver for goal-driven tasks (use it instead of Playwright): one natural-language goal, an indexed action space...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/browser-use/jev-ultrafast"
  },
  {
    "id": "browser-use",
    "name": "Browser Use",
    "section": "browser",
    "desc": "Fallback browser agent when jev-ultrafast is unavailable (no TypeSafe key): Python library driving Chrome with any OpenAI-compa...",
    "required": false,
    "stars": null,
    "repo": "https://github.com/browser-use/browser-use"
  },
  {
    "id": "crawlee",
    "name": "Crawlee",
    "section": "browser",
    "desc": "Crawling framework (Node): HTTP and headless crawlers, request queues, retries, proxy rotation, storage. Respect robots.txt, te...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/apify/crawlee"
  },
  {
    "id": "scrapling",
    "name": "Scrapling",
    "section": "browser",
    "desc": "Python scraping with adaptive selectors that survive page changes, plus fetchers. Same rules: robots.txt, terms, rate limits, n...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/D4Vinci/Scrapling"
  },
  {
    "id": "playwright-test",
    "name": "Playwright",
    "section": "browser",
    "desc": "E2E test runner only (not the browser automation core). jev-ultrafast is the primary browser driver; Playwright is a secondary...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/microsoft/playwright"
  },
  {
    "id": "react-spring",
    "name": "React Spring",
    "section": "animation",
    "desc": "Spring-physics based React animation library. Use for physics-driven, interruptible motion where springs read better than keyfr...",
    "required": false,
    "stars": 29200,
    "repo": "https://github.com/pmndrs/react-spring"
  },
  {
    "id": "react-flip-toolkit",
    "name": "React Flip Toolkit",
    "section": "animation",
    "desc": "Lightweight magic-move library for configurable layout transitions (FLIP technique). Ideal for list reordering and shared-eleme...",
    "required": false,
    "stars": 4200,
    "repo": "https://github.com/aholachek/react-flip-toolkit"
  },
  {
    "id": "dotlottie-web",
    "name": "dotLottie Web",
    "section": "animation",
    "desc": "High-performance Lottie and dotLottie player powered by Rust + WASM. Use for designer-authored vector animation on the web.",
    "required": false,
    "stars": 884,
    "repo": "https://github.com/LottieFiles/dotlottie-web"
  },
  {
    "id": "motion",
    "name": "Motion",
    "section": "animation",
    "desc": "Animation for React/JS/Vue: layout animations, gestures, springs, scroll-linked motion. First choice for React UI motion.",
    "required": true,
    "stars": null,
    "repo": "https://github.com/motiondivision/motion"
  },
  {
    "id": "anime",
    "name": "Anime.js",
    "section": "animation",
    "desc": "Framework-free timelines for DOM, SVG and CSS: staggers, SVG path drawing, sequenced animation.",
    "required": true,
    "stars": null,
    "repo": "https://github.com/juliangarnier/anime"
  },
  {
    "id": "animate-css",
    "name": "Animate.css",
    "section": "animation",
    "desc": "Drop-in CSS keyframe classes for entrance/exit/attention effects when a JS animation library is not justified. Honour prefers-r...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/animate-css/animate.css"
  },
  {
    "id": "12-principles-animation",
    "name": "12 Principles of Animation",
    "section": "animation",
    "desc": "Apply Disney 12 principles of animation to UI: squash and stretch, anticipation, staging, ease in/out, arc, secondary action, t...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/raphaelsalaja/ui-skills"
  },
  {
    "id": "angular",
    "name": "Angular",
    "section": "design",
    "desc": "Batteries-included TypeScript web framework with dependency injection, routing and forms. Use when a project already targets An...",
    "required": false,
    "stars": 101000,
    "repo": "https://github.com/angular/angular"
  },
  {
    "id": "open-design",
    "name": "Open Design",
    "section": "design",
    "desc": "Local-first design engine that turns a coding agent into a design engine: prototypes, landing pages, dashboards, slides, exports.",
    "required": false,
    "stars": 98100,
    "repo": "https://github.com/nexu-io/open-design"
  },
  {
    "id": "tailwindcss",
    "name": "Tailwind CSS",
    "section": "design",
    "desc": "Utility-first CSS framework for rapid, consistent UI. Composable, purge-friendly, and the base for shadcn/ui and daisyUI.",
    "required": false,
    "stars": 97700,
    "repo": "https://github.com/tailwindlabs/tailwindcss"
  },
  {
    "id": "semantic-ui",
    "name": "Semantic UI",
    "section": "design",
    "desc": "Component framework built around natural-language principles. Reference for semantic naming and component APIs.",
    "required": false,
    "stars": 51000,
    "repo": "https://github.com/Semantic-Org/Semantic-UI"
  },
  {
    "id": "bulma",
    "name": "Bulma",
    "section": "design",
    "desc": "Modern Flexbox-based CSS framework with no JavaScript dependency. Good when a project wants CSS-only components.",
    "required": false,
    "stars": 50100,
    "repo": "https://github.com/jgthms/bulma"
  },
  {
    "id": "daisyui",
    "name": "daisyUI",
    "section": "design",
    "desc": "Component library on top of Tailwind CSS. Semantic class names for buttons, cards, modals and themes.",
    "required": false,
    "stars": 42500,
    "repo": "https://github.com/saadeghi/daisyui"
  },
  {
    "id": "pico-css",
    "name": "Pico CSS",
    "section": "design",
    "desc": "Minimal CSS framework for semantic HTML. Near-zero classes, dark mode built in — excellent for content-first pages.",
    "required": false,
    "stars": 16900,
    "repo": "https://github.com/picocss/pico"
  },
  {
    "id": "bootstrap",
    "name": "Bootstrap",
    "section": "design",
    "desc": "Responsive grid, components and utilities. Use when the project already has it, or needs an accessible component baseline witho...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/twbs/bootstrap"
  },
  {
    "id": "font-awesome",
    "name": "Font Awesome",
    "section": "design",
    "desc": "Icon set (free tier) as SVG, web font or JS. Import only the icons used.",
    "required": true,
    "stars": null,
    "repo": "https://github.com/FortAwesome/Font-Awesome"
  },
  {
    "id": "css-gg",
    "name": "css.gg",
    "section": "design",
    "desc": "Pure-CSS/SVG icons with no font or JS, for tiny bundles. Custom licence: read https://css.gg/licence.txt before shipping.",
    "required": true,
    "stars": null,
    "repo": "https://github.com/astrit/css.gg"
  },
  {
    "id": "impeccable",
    "name": "Impeccable",
    "section": "design",
    "desc": "Agent design-quality skill: design vocabulary, audits and anti-patterns for front-end work. Writes provider hooks, so it is ins...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/pbakaus/impeccable"
  },
  {
    "id": "front-end-checklist",
    "name": "Front-End Checklist",
    "section": "design",
    "desc": "Pre-launch checklist: head/meta/SEO, accessibility, performance, images, CSS, JS. Use as the web launch gate next to lifecycle/...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/thedaviddias/Front-End-Checklist"
  },
  {
    "id": "app-ideas",
    "name": "App Ideas",
    "section": "design",
    "desc": "Tiered app ideas with user stories. Use when the goal is vague or asks for ideas; turn the chosen idea into acceptance criteria.",
    "required": true,
    "stars": null,
    "repo": "https://github.com/florinpop17/app-ideas"
  },
  {
    "id": "emil-design-eng",
    "name": "Emil Design Engineering",
    "section": "design",
    "desc": "UI polish, micro-interactions, and premium design engineering using Framer Motion and CSS. Makes interfaces feel intentional an...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/emilkowalski/skills"
  },
  {
    "id": "make-interfaces-better",
    "name": "Make Interfaces Feel Better",
    "section": "design",
    "desc": "Small UX improvements that make interfaces significantly better: timing, spacing, contrast, focus management, scroll behavior,...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/emilkowalski/skills"
  },
  {
    "id": "react-doctor",
    "name": "React Doctor",
    "section": "design",
    "desc": "Automatically finds React performance issues, unnecessary re-renders, bundle bloat, and hooks misuse. Uses Million.js for autom...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/aidenybai/million"
  },
  {
    "id": "fixing-accessibility",
    "name": "Fixing Accessibility",
    "section": "design",
    "desc": "Comprehensive accessibility fixes: ARIA labels, keyboard navigation, focus management, color contrast, screen reader support, W...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/ibelick/ui-skills"
  },
  {
    "id": "shadcn-ui",
    "name": "shadcn/ui",
    "section": "design",
    "desc": "Beautifully designed, accessible, copy-and-paste UI components built with Radix UI and Tailwind CSS. Not a component library —...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/shadcn-ui/ui"
  },
  {
    "id": "flutter",
    "name": "Flutter",
    "section": "backend",
    "desc": "Cross-platform UI toolkit for mobile, web and desktop from one Dart codebase. Consider alongside React Native/Expo for mobile g...",
    "required": false,
    "stars": 179000,
    "repo": "https://github.com/flutter/flutter"
  },
  {
    "id": "flask",
    "name": "Flask",
    "section": "backend",
    "desc": "Python micro-framework for web applications. Minimal core with a large extension ecosystem; good for Python services and APIs.",
    "required": false,
    "stars": 74800,
    "repo": "https://github.com/pallets/flask"
  },
  {
    "id": "hono",
    "name": "Hono",
    "section": "backend",
    "desc": "Ultrafast web framework built on Web Standards. Runs on Cloudflare Workers, Deno, Bun and Node — ideal for edge APIs.",
    "required": false,
    "stars": 32300,
    "repo": "https://github.com/honojs/hono"
  },
  {
    "id": "phoenix",
    "name": "Phoenix",
    "section": "backend",
    "desc": "Elixir web framework with first-class realtime (LiveView, channels). Strong for concurrent, realtime applications.",
    "required": false,
    "stars": 23200,
    "repo": "https://github.com/phoenixframework/phoenix"
  },
  {
    "id": "react-native",
    "name": "React Native",
    "section": "backend",
    "desc": "Native Android/iOS apps in React. Start new apps through Expo, which React Native recommends.",
    "required": true,
    "stars": null,
    "repo": "https://github.com/react/react-native"
  },
  {
    "id": "expo",
    "name": "Expo",
    "section": "backend",
    "desc": "React Native framework: Expo Router, native modules, dev builds, EAS Build for Android APK/AAB. Add packages with `npx expo ins...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/expo/expo"
  },
  {
    "id": "appwrite",
    "name": "Appwrite",
    "section": "backend",
    "desc": "Self-hostable backend: auth, databases, storage, functions, realtime. SDKs: appwrite (web), react-native-appwrite (mobile), nod...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/appwrite/appwrite"
  },
  {
    "id": "prisma",
    "name": "Prisma ORM",
    "section": "backend",
    "desc": "Type-safe ORM and migrations for Postgres, MySQL/TiDB, SQLite, SQL Server, MongoDB. Never run destructive migrations against sh...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/prisma/orm"
  },
  {
    "id": "redis",
    "name": "Redis",
    "section": "backend",
    "desc": "In-memory store for cache, sessions, rate limits, queues, pub/sub and streams. Set TTLs; never cache per-user data under shared...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/redis/redis"
  },
  {
    "id": "meilisearch",
    "name": "Meilisearch",
    "section": "backend",
    "desc": "Typo-tolerant full-text, faceted and hybrid search. Master key stays server-side; clients get scoped search keys.",
    "required": true,
    "stars": null,
    "repo": "https://github.com/meilisearch/meilisearch"
  },
  {
    "id": "clickhouse",
    "name": "ClickHouse",
    "section": "backend",
    "desc": "Columnar OLAP database for analytics, events, logs and time series. Client: @clickhouse/client. Not a transactional store.",
    "required": true,
    "stars": null,
    "repo": "https://github.com/ClickHouse/ClickHouse"
  },
  {
    "id": "tidb",
    "name": "TiDB",
    "section": "backend",
    "desc": "Distributed MySQL-compatible SQL database. Use when a single MySQL node will not scale; connect with any MySQL client or Prisma...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/pingcap/tidb"
  },
  {
    "id": "netdata",
    "name": "Netdata",
    "section": "backend",
    "desc": "Per-second infrastructure and application monitoring with alerts. Keep the dashboard on localhost or behind auth.",
    "required": true,
    "stars": null,
    "repo": "https://github.com/netdata/netdata"
  },
  {
    "id": "x64dbg",
    "name": "x64dbg",
    "section": "security",
    "desc": "Open-source user-mode debugger for Windows, optimized for reverse engineering and malware analysis. Reference for binary analysis.",
    "required": false,
    "stars": 49600,
    "repo": "https://github.com/x64dbg/x64dbg"
  },
  {
    "id": "shannon",
    "name": "Shannon",
    "section": "security",
    "desc": "AI pentester for web apps and APIs: reads source, identifies attack vectors, executes real exploits to prove vulnerabilities be...",
    "required": false,
    "stars": 48400,
    "repo": "https://github.com/KeygraphHQ/shannon"
  },
  {
    "id": "trivy",
    "name": "Trivy",
    "section": "security",
    "desc": "Find vulnerabilities, misconfigurations, secrets and SBOM issues across containers, Kubernetes, IaC and repositories. Primary d...",
    "required": false,
    "stars": 38100,
    "repo": "https://github.com/aquasecurity/trivy"
  },
  {
    "id": "web-check",
    "name": "Web-Check",
    "section": "security",
    "desc": "All-in-one OSINT tool for analysing any website: headers, DNS, TLS, cookies, security posture. Use for passive recon of authori...",
    "required": false,
    "stars": 34900,
    "repo": "https://github.com/lissy93/web-check"
  },
  {
    "id": "gitleaks",
    "name": "Gitleaks",
    "section": "security",
    "desc": "Detect hardcoded secrets and credentials in git history and working trees. Gate on findings before release.",
    "required": false,
    "stars": 29500,
    "repo": "https://github.com/gitleaks/gitleaks"
  },
  {
    "id": "trufflehog",
    "name": "TruffleHog",
    "section": "security",
    "desc": "Find, verify and analyze leaked credentials. Verification reduces false positives versus plain regex scanners.",
    "required": false,
    "stars": 28100,
    "repo": "https://github.com/trufflesecurity/trufflehog"
  },
  {
    "id": "spiderfoot",
    "name": "SpiderFoot",
    "section": "security",
    "desc": "Automates OSINT for threat intelligence and attack-surface mapping. Reference for external footprint analysis.",
    "required": false,
    "stars": 22500,
    "repo": "https://github.com/smicallef/spiderfoot"
  },
  {
    "id": "rustscan",
    "name": "RustScan",
    "section": "security",
    "desc": "Modern port scanner that feeds results into Nmap. Fast discovery phase for authorized network testing.",
    "required": false,
    "stars": 20500,
    "repo": "https://github.com/bee-san/RustScan"
  },
  {
    "id": "fail2ban",
    "name": "Fail2ban",
    "section": "security",
    "desc": "Intrusion-prevention daemon that bans hosts causing repeated authentication failures. Standard server hardening.",
    "required": false,
    "stars": 18700,
    "repo": "https://github.com/fail2ban/fail2ban"
  },
  {
    "id": "skillspector",
    "name": "NVIDIA SkillSpector",
    "section": "security",
    "desc": "Security scanner for AI agent skills: detects prompt injection, data exfiltration and supply-chain risk in Claude/Codex/MCP ski...",
    "required": false,
    "stars": 18300,
    "repo": "https://github.com/NVIDIA/SkillSpector"
  },
  {
    "id": "wazuh",
    "name": "Wazuh",
    "section": "security",
    "desc": "Open-source XDR and SIEM platform for endpoints and cloud workloads. Unified detection, response and compliance monitoring.",
    "required": false,
    "stars": 17000,
    "repo": "https://github.com/wazuh/wazuh"
  },
  {
    "id": "lynis",
    "name": "Lynis",
    "section": "security",
    "desc": "Security auditing and hardening tool for Linux, macOS and UNIX. Compliance-oriented (HIPAA, ISO 27001, PCI DSS).",
    "required": false,
    "stars": 16400,
    "repo": "https://github.com/CISOfy/lynis"
  },
  {
    "id": "prowler",
    "name": "Prowler",
    "section": "security",
    "desc": "Open-source cloud security platform: automates security and compliance assessment across AWS, Azure and GCP.",
    "required": false,
    "stars": 14900,
    "repo": "https://github.com/prowler-cloud/prowler"
  },
  {
    "id": "scapy",
    "name": "Scapy",
    "section": "security",
    "desc": "Python packet manipulation program and library. Craft, send, sniff and dissect network traffic for protocol testing.",
    "required": false,
    "stars": 12600,
    "repo": "https://github.com/secdev/scapy"
  },
  {
    "id": "codex-security",
    "name": "OpenAI Codex Security",
    "section": "security",
    "desc": "Automated security analysis and vulnerability detection using AI-powered code scanning. Integrates with CI/CD pipelines for rea...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/openai/codex-security"
  },
  {
    "id": "sqlmap",
    "name": "SQLMap",
    "section": "security",
    "desc": "Automated SQL injection detection and database takeover tool. USE ONLY AGAINST EXPLICITLY AUTHORIZED TARGETS in disposable test...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/sqlmapproject/sqlmap"
  },
  {
    "id": "awesome-hacking",
    "name": "Awesome Hacking",
    "section": "security",
    "desc": "Curated collection of hacking resources, security tools, CTFs, and offensive security knowledge. Use as a security knowledge/re...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/Hack-with-Github/Awesome-Hacking"
  },
  {
    "id": "cloudflare-security-audit",
    "name": "Cloudflare Security Audit Skill",
    "section": "security",
    "desc": "Security auditing workflows for Cloudflare-protected applications. Includes WAF rule analysis, DDoS mitigation review, zero-tru...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/cloudflare/security-audit-skill"
  },
  {
    "id": "anthropics-skills",
    "name": "Anthropic Agent Skills",
    "section": "quality",
    "desc": "Public reference repository for the Agent Skills format. The canonical model for how a skill declares scope and triggers.",
    "required": false,
    "stars": 178000,
    "repo": "https://github.com/anthropics/skills"
  },
  {
    "id": "ponytail",
    "name": "Ponytail",
    "section": "quality",
    "desc": "Agent skill that enforces YAGNI: the best code is the code you never wrote. Useful as a minimalism counterweight during planning.",
    "required": false,
    "stars": 146000,
    "repo": "https://github.com/DietrichGebert/ponytail"
  },
  {
    "id": "addyosmani-agent-skills",
    "name": "Addy Osmani Agent Skills",
    "section": "quality",
    "desc": "Production-grade engineering skills for AI coding agents. Strong reference for code-quality and review workflows.",
    "required": false,
    "stars": 99000,
    "repo": "https://github.com/addyosmani/agent-skills"
  },
  {
    "id": "awesome-claude-skills",
    "name": "Awesome Claude Skills",
    "section": "quality",
    "desc": "Curated list of Claude skills, resources and tools for customizing agent workflows. Discovery source for new capabilities.",
    "required": false,
    "stars": 75600,
    "repo": "https://github.com/ComposioHQ/awesome-claude-skills"
  },
  {
    "id": "humanizer",
    "name": "Humanizer",
    "section": "quality",
    "desc": "Agent skill that removes signs of AI-generated writing from text. Use when polishing user-facing copy and docs.",
    "required": false,
    "stars": 52000,
    "repo": "https://github.com/blader/humanizer"
  },
  {
    "id": "diagram-design",
    "name": "Diagram Design",
    "section": "quality",
    "desc": "Editorial diagram design skill producing self-contained HTML + SVG. Complements Archify for crisp architecture visuals.",
    "required": false,
    "stars": 42400,
    "repo": "https://github.com/cathrynlavery/diagram-design"
  },
  {
    "id": "wshobson-agents",
    "name": "wshobson/agents",
    "section": "quality",
    "desc": "Multi-harness agentic plugin marketplace and subagent patterns for Claude Code, Codex and Cursor. Reference for agent decomposi...",
    "required": false,
    "stars": 40000,
    "repo": "https://github.com/wshobson/agents"
  },
  {
    "id": "awesome-copilot",
    "name": "GitHub Awesome Copilot",
    "section": "quality",
    "desc": "Community-contributed instructions, agents and skills from GitHub. Reference for instruction-file conventions.",
    "required": false,
    "stars": 39400,
    "repo": "https://github.com/github/awesome-copilot"
  },
  {
    "id": "awesome-agent-skills",
    "name": "Awesome Agent Skills",
    "section": "quality",
    "desc": "1000+ agent skills from official teams and the community, compatible with Claude Code, Codex, Gemini CLI and Cursor.",
    "required": false,
    "stars": 34900,
    "repo": "https://github.com/VoltAgent/awesome-agent-skills"
  },
  {
    "id": "book-to-skill",
    "name": "Book to Skill",
    "section": "quality",
    "desc": "Turn a technical book PDF into a reusable agent skill. Reference for building durable knowledge skills from long-form sources.",
    "required": false,
    "stars": 32400,
    "repo": "https://github.com/virgiliojr94/book-to-skill"
  },
  {
    "id": "keploy",
    "name": "Keploy",
    "section": "quality",
    "desc": "Records real API traffic (HTTP, databases, queues) as replayable tests and mocks: `keploy record -c \"<run app>\"`, then `keploy...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/keploy/keploy"
  },
  {
    "id": "open-code-review",
    "name": "Open Code Review",
    "section": "quality",
    "desc": "Precision-first AI code review CLI (`ocr`). Reads its model from OCR_LLM_URL / OCR_LLM_TOKEN / OCR_LLM_MODEL, which `dip exec`...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/alibaba/open-code-review"
  },
  {
    "id": "archify",
    "name": "Archify",
    "section": "quality",
    "desc": "Agent skill that turns an architecture, plan or idea into a self-contained interactive HTML diagram. Use to explain a system or...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/tt-a1i/archify"
  },
  {
    "id": "superpowers",
    "name": "Superpowers",
    "section": "quality",
    "desc": "Skills for brainstorming, writing plans, TDD, systematic debugging, subagent-driven development and verification before complet...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/obra/superpowers"
  },
  {
    "id": "mattpocock-skills",
    "name": "Matt Pocock skills",
    "section": "quality",
    "desc": "Engineering and productivity skills for coding agents (TypeScript-heavy). Pick the ones you need; include setup-matt-pocock-ski...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/mattpocock/skills"
  },
  {
    "id": "claude-plugins-official",
    "name": "Claude plugins (official)",
    "section": "quality",
    "desc": "Anthropic's plugin marketplace. Useful here: code-review, pr-review-toolkit, feature-dev, frontend-design, code-simplifier, and...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/anthropics/claude-plugins-official"
  },
  {
    "id": "awesome-claude-code",
    "name": "Awesome Claude Code",
    "section": "quality",
    "desc": "Curated list of Claude Code skills, hooks, commands and workflows. Search it when a need is not covered by this catalog.",
    "required": true,
    "stars": null,
    "repo": "https://github.com/hesreallyhim/awesome-claude-code"
  },
  {
    "id": "kubernetes-the-hard-way",
    "name": "Kubernetes The Hard Way",
    "section": "quality",
    "desc": "Step-by-step Kubernetes bootstrap for understanding every component (certs, etcd, control plane, networking). Learning referenc...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/kelseyhightower/kubernetes-the-hard-way"
  },
  {
    "id": "awesome-scalability",
    "name": "Awesome Scalability",
    "section": "quality",
    "desc": "Patterns for scalable, reliable, performant large systems, with real-world case studies. Read before choosing caches, queues, s...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/binhnguyennus/awesome-scalability"
  },
  {
    "id": "n8n",
    "name": "n8n",
    "section": "quality",
    "desc": "Self-hostable workflow automation with 400+ integrations and AI nodes. Keep credentials in n8n's store, never in workflow JSON...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/n8n-io/n8n"
  },
  {
    "id": "ruflo",
    "name": "Ruflo",
    "section": "quality",
    "desc": "Multi-agent swarm orchestration for Claude Code (memory, swarms, MCP). Lite path: `/plugin marketplace add ruvnet/ruflo` then `...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/ruvnet/ruflo"
  },
  {
    "id": "paperclip",
    "name": "Paperclip",
    "section": "quality",
    "desc": "App for running and managing teams of AI agents for ongoing work. Installed with its own verified installer (download install.s...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/paperclipai/paperclip"
  },
  {
    "id": "agent-reach",
    "name": "Agent Reach",
    "section": "quality",
    "desc": "Web research and information-gathering capability for agents: reach out to external sources, gather better context before plann...",
    "required": true,
    "stars": null,
    "repo": "https://github.com/Panniantong/agent-reach"
  }
];
